Monitoring_Script/Monitoring_Script/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^pinger/',include('pinger.urls')),
    url(r'^admin/', admin.site.urls),
]

Monitoring_Script/pinger/urls.py
from django.conf.urls import url

from . import views

app_name = 'pinger'
urlpatterns = [
        url(r'^add/$',views.add, name = 'add'),
        url(r'^$',views.index,name = 'index'),
        url(r'^remove/(?P<name>\w+)/$', views.remove, name = 'remove'),
        url(r'^pause/(?P<name>\w+)/$', views.pause, name = 'pause'),
        url(r'^restart/(?P<name>\w+)/$',views.restart, name = 'restart'),
        url(r'^rename/(?P<name>\w+)/$',views.rename, name = 'rename'),
        url(r'^(?P<name>\w+)/$', views.detail, name = 'detail'),
        
        ]

Monitoring_Script/pinger/models.py
from django.db import models

class Device(models.Model):
    name = models.CharField(max_length = 21)
    web_address = models.CharField(max_length = 50)
    startup_time = models.IntegerField()
    stop_time = models.IntegerField()
    status = models.BooleanField(default = True)
    
    def __str__(self):
        return (self.name)
    
class Log(models.Model):
    device = models.ForeignKey(Device,on_delete = models.CASCADE)
    period = models.CharField(max_length = 20)
    uptime = models.IntegerField(default = 0)
    downtime = models.IntegerField(default = 0)
    log_msg = models.CharField(max_length = 200,default = "No log created yet")
    
    def __str__(self):
        return (self.device)

Monitoring_Script/pinger/views.py
from .models import Device

from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_protect

import time,threading
import requests

def status():
    while 1:
        for device in Device.objects.all():
            address = device.web_address
            try:
                res = requests.get(address) #response
                if res.status_code == 200: device.status = True; 
                else: device.status = False;  
                device.save()
            except:
                device.status = False;  
                device.save()

@csrf_protect
def index(request):
    devices = Device.objects.all()
    tmp = [ "Correct" for r_thread in threading.enumerate() if r_thread.getName() == "status"]
    if len(tmp):
        "Everything is okay"
    else:
        #A thread named status has to be created that keeps checking if the webservers are up
        new_thread = threading.Thread(target = status, name = "status"); new_thread.start()
    template = loader.get_template("pinger/index.htm")
    context = {
            "devices": devices
            }
    tmp = template.render(context,request)
    return HttpResponse(tmp)

def detail(request,name):
    device = get_object_or_404(Device,name = name); 
    return HttpResponse(device.web_address)

@csrf_protect
def add(request):
    name = request.POST.get("device name")
    address = request.POST.get("web address")
    s_time = time.time()
    new_d = Device(name = name, web_address = address, startup_time = s_time, stop_time = 0,status = False) #new device
    new_d.save()
    return HttpResponseRedirect(reverse('pinger:index',))

def remove(request,name):
    device = get_object_or_404(Device,name = name); device.delete()
    return HttpResponseRedirect(reverse('pinger:index',))

def pause(request,name):
    return HttpResponse("This Feature is not yet available")

def restart(request,name):
    return HttpResponse("This Feature is not yet available")

def rename (request,name):
    return HttpResponse("This Feature is not yet available")

def dev_log(request,name):
    return HttpResponse("This Feature is not yet available")

Monitoring_Script/pinger/templates/pinger/index.htm
<!DOCTYPE html>
<html>
<h1>Pinger</h1>


{% if message %}
<font size = "3"
color = "red">{{message}}
</font>
{% endif %}

<div id ="Devices">
    {% if devices %}
        {% for device in devices %}
        <li>
            <a 
                href="{% url 'pinger:detail' device.name %}" style = "text-decoration: none">{{ device.name }}
            </a>
                {% if device.status %}
                   ✅
                {% else %}
                   ❌
        {% endif %}
    </li>

<form>
  <button formaction={% url 'pinger:remove' device.name %}>remove</button>
  <button formaction={% url 'pinger:rename' device.name %}>rename</button>
  {% if device.status %}
  <button formaction={% url 'pinger:pause' device.name %}>pause</button>
  {% else %}
  <button formaction={% url 'pinger:restart' device.name %}>restart</button>
  {% endif %}
</form>
<br>
{% endfor %} 
</ul>
{% else %}
<b> No devices added yet </b>
{% endif %}
<br><br><br>
</div>

<form method = "POST" action = {% url 'pinger:add' %}>
{% csrf_token %}
 <fieldset>
  <legend>Add another device for monitoring</legend>
  Device Name :<br>
  <input type="text" name="device name" ><br><br>
  Device Web address:<br>
  <input type="text" name="web address" placeholder = "include http header" ><br>
  <br>
  <input type="submit" value="Add Device">
 </fieldset>
</form>

<script type = "text/javascript">
    window.onload = setupRefresh;
    
    function setupRefresh(){
        setInterval("refreshBlock();",1000);
    }
    
    function refreshBlock() {
    
        var request = new XMLHttpRequest();
        request.open("GET","http://127.0.0.1:8000/pinger/",true);
        request.onload = function() {
        if (request.status == 200) {
            var resp = request.responseText;
            var begin = resp.indexOf("<div");
            var end = resp.indexOf("</div>");
            var test = resp.slice(begin,end);
            
            document.getElementById("Devices").innerHTML = resp.slice(begin,end);
            
         }
        };
        
        request.send();   
    }
</script>

</html>

Monitoring_Script/pinger/templates/pinger/list_details.htm
<a href={% url 'goals:index' user.username "empty" %}><h1>mLG</h1></a><!-- Home page of Users -->

<!-- Displays all goals under the personal list of a user, including remove and rename button -->
{{ category.title }}
{% if goals %}
<ul>
{% for g in goals%}
<li>{{ g.text }}</li>
<form>
  <button formaction={% url 'goals:remove' user.username category.id g.id %}>remove</button>
  <button formaction={% url 'goals:rename' user.username category.id g.id %}>rename</button>
</form>
{% endfor %}
</ul>
{% else %}
<p>No goals added yet.</p>
{% endif %}

<!-- A text box for creating a new goal -->
<form action = {% url 'goals:add' user.username category.id %} >
  New goal<br>
  <input type="text" name="new_goal"><br>
  <input type="submit" value="Create Goal">
</form>

Monitoring_Script/pinger/templates/pinger/register.htm
<h1>Welcometo mLG</h1>
make LIFE GOOD by making your LIFE GOALS come true
<br><br>

<!-- Notification to mLG Users-->
{% if message %}
<font size = "3"
color = "red">{{message}}
</font>
{% endif %}

<!-- Sign up -->
<form action= {% url 'goals:sign_up' %}  method = POST>
{% csrf_token %}
  <fieldset>
    <legend>SIGN-UP:</legend>
    EMAIL:<br>
    <input type="email" name="email"><br>
    USER NAME:<br>
    <input type="text" name="user name"><br>
    PASSWORD:<br>
    <input type="password" name="password"><br><br>
    <input type="submit" value="Submit">
  </fieldset>
</form>

<!-- Sign in -->
<form action= {% url 'goals:sign_in' %}  method = POST>
{% csrf_token %}
  <fieldset>
    <legend>SIGN-IN:</legend>
    USERNAME:<br>
    <input type="text" name="user name"><br>
    PASSWORD:<br>
    <input type="password" name="password"><br><br>
    <input type="submit" value="Submit">
  </fieldset>
</form>

Monitoring_Script/pinger/templates/pinger/rename.htm
<a href={% url 'goals:index' user.username "empty" %}><h1>mLG</h1></a> <!-- Home page of Users -->

<!-- A text box for renaming lists -->
{% if list_text %}
<form action = {% url 'goals:save' user.username list_text.id 0 %} -->
  Enter New Name<br>
  <input type="text" name="new_name" value = {{list_text.title}}><br>
  <input type="submit" value="Save">
</form>

<!-- A text box for renaming goals -->
{% else %}
<form action = {% url 'goals:save' user.username goals_text.category.id goals_text.id %} >
  Enter New Name<br>
  <input type="text" name="new_name" value = {{goals_text.text}}><br>
  <input type="submit" value="Save">
{% endif %}

Monitoring_Script/pinger/templates/pinger/test_run.html
<select name="cars">
  <form>
  <button formaction={% url 'goals:remove' category.id g.id %}>remove</button>
 </form>
</select>